birdscollector/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')), # Mount the app's routes at the root URL
\
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('birds/', views.bird_index, name='bird-index'),
    path('birds/<int:bird_id>/', views.bird_detail, name='bird-detail'),
    path('birds/create/', views.BirdCreate.as_view(), name='bird-create'),
    path('birds/<int:pk>/update/', views.BirdUpdate.as_view(), name='bird-update'),
    path('birds/<int:pk>/delete/', views.BirdDelete.as_view(), name='bird-delete'),
    path('cats/<int:bird_id>/add-feeding/', views.add_feeding,name='add-feeding'),

    

]

main_app/models.py
from django.db import models
from django.urls import reverse



# A tuple of 2-tuples added above our models
MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner')
)

# Create your models here.

class Bird(models.Model):
    name = models.CharField(max_length=100)
    breed = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    age = models.IntegerField()

  # new code below
    def __str__(self):
        return self.name
    

  # Define a method to get the URL for this particular cat instance
    def get_absolute_url(self):
        # Use the 'reverse' function to dynamically find the URL for viewing this cat's details
        return reverse('cat-detail', kwargs={'cat_id': self.id})
    

# Add new Feeding model below Cat model

class Feeding(models.Model):
    date = models.DateField('feeding date')
    meal = models.CharField(
        max_length=1,
        # add the 'choices' field option
        choices=MEALS,
        # set the default value for meal to be 'B'
        default=MEALS[0][0]
    )

# Create a cat_id column for each feeding in the database
    bird = models.ForeignKey(Bird, on_delete=models.CASCADE)

    def __str__(self):
        # Nice method for obtaining the friendly value of a Field.choice
        return f"{self.get_meal_display()} on {self.date}"
    class Meta:
        ordering = ['-date']  # This line makes the newest feedings appear first

main_app/forms.py
from django import forms
from .models import Feeding

class FeedingForm(forms.ModelForm):
    class Meta:
        model = Feeding
        fields = ['date', 'meal']
        widgets = {
            'date': forms.DateInput(
                format=('%Y-%m-%d'),
                attrs={
                    'placeholder': 'Select a date',
                    'type': 'date'
                }
            ),
        }

main_app/views.py
# main_app/views.py

from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView,UpdateView, DeleteView
from .models import Bird
from .forms import FeedingForm
# class Bird:
#     def __init__(self, name, breed, description, age):
#         self.name = name
#         self.breed = breed
#         self.description = description
#         self.age = age

# # Create a list of Bird instances
# birds = [
#     Bird('Amazon Parrot','baby Amazon Parrot' ,'Chatterbox jungle clown .', 12),
#     Bird('Arican Gray', 'baby Arican Gray','Feathery smartmouth diva.', 10),
#     Bird('Bailey', 'baby Bailey', 'Barky cuddle monster.', 2),
#     Bird('Black Falcon','baby Black Falcon' , 'Sneaky screecher.', 6),
# ]

# main-app/views.py

class BirdCreate(CreateView):
    model = Bird
    fields = '__all__'


class BirdUpdate(UpdateView):
    model = Bird
    # Let's disallow the renaming of a cat by excluding the name field!
    fields = ['breed', 'description', 'age']

class BirdDelete(DeleteView):
    model = Bird
    success_url = '/birds/'



def home(request):
    return render(request, 'home.html')


def about(request):
          return render(request, 'about.html')

def bird_index(request):
    birds = Bird.objects.all()  # look familiar?
    return render(request, 'birds/index.html', {'birds': birds})


def bird_detail(request, bird_id):
    bird = Bird.objects.get(id=bird_id)
    feeding_form = FeedingForm()
    return render(request, 'birds/detail.html', {
        'bird': bird, 'feeding_form': feeding_form
    })


def add_feeding(request, bird_id):
    # create a ModelForm instance using the data in request.POST
    form = FeedingForm(request.POST)
    # validate the form
    if form.is_valid():
        new_feeding = form.save(commit=False)
        new_feeding.bird_id = bird_id
        new_feeding.save()
    return redirect('bird-detail', bird_id=bird_id)

main_app/templates/about.html
{% extends 'base.html' %} 
{% block content %}
<h1>About the Bird Collector</h1>
<hr />
<p class="page-content">
    Known for its remarkable cognitive abilities, this parrot can solve problems and understand complex tasks.
</p>
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" type="image/png" href="" />
    <title>Birds Collector</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />

    <link
    rel="shortcut icon"
    type="image/png"
    href="{% static 'images/splash.svg' %}"
  />
  

    {% block head %} 
    {% endblock %}
  </head>
  <body>
    <header>
      <div class="header-logo-container">
        <a href="/">
            <img src="{% static 'images/header-logo.svg' %}" alt="The bird Collector Logo" />

        </a>
      </div>
      <nav>
        <ul>
            <li><a href="/">Home</a></li>  
            <li><a href="{% url 'bird-index' %}">All Birds</a></li>
            <li><a href="{% url 'bird-create' %}">Add a Bird</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
            
            
        </ul>
      </nav>
    </header>
    <main>
     {% block content %} 
     {% endblock %}
     </main>
  </body>
</html>

main_app/templates/birds/detail.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/cats/cat-detail.css' %}" />
{% endblock %} 
  {% block content %}
<section class="cat-container">
  <div class="cat-img">
    <img src="{% static 'images/sk8r-boi-cat.svg' %}" alt="A skater boy cat" />
  </div>
  <div class="cat-details">
    <h1>{{ bird.name }}</h1>
    {% if bird.age > 0 %}
      <h2>A {{ bird.age }} year old {{ bird.breed }}</h2>
    {% else %}
      <h2>A {{ bird.breed }} kitten.</h2>
    {% endif %}
    <p>{{ bird.description }}</p>


   <div class="cat-actions">
    <a href="{% url 'bird-update' bird.id %}" class="btn warn">Edit</a>
    <a href="{% url 'bird-delete' bird.id %}" class="btn danger">Delete</a>
  </div>
</div>
</section>

<!-- Existing cat-container above -->
<div class="feedings-toy-container">
  <section class="feedings">
    <div class="subsection-title">
      <h2>Feedings</h2>
      <img
        src="{% static 'images/cat-cone.svg' %}"
        alt="An ice cream cone cat"
      />
      <img src="{% static 'images/cat-onigiri.svg' %}" alt="A cat as onigiri" />
      <img
        src="{% static 'images/kitty-kabob.svg' %}"
        alt="A kabob of kittens"
      />
    </div>

    <h3>Add a Feeding</h3>
    <form
      action="{% url 'add-feeding' bird.id %}"
      method="post"
      class="subsection-content"
      autocomplete="off"
    >
      {% csrf_token %} 
      {{ feeding_form.as_p }}
      <button type="submit" class="btn submit">Add Feeding</button>
    </form>

    <h3>Past Feedings</h3>
    {% if bird.feeding_set.all.count %}
    <table>
      <thead>
        <tr>
          <th>Date</th>
          <th>Meal</th>
        </tr>
      </thead>
      <tbody>
        {% for feeding in bird.feeding_set.all %}
          <tr>
            <td>{{feeding.date}}</td>
            <td>{{feeding.get_meal_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
  <div class="subsection-content">
    <p>⚠️ {{bird.name}} has not been fed!</p>
  </div>
{% endif %}

  </section>
</div>

{% endblock %}

main_app/templates/birds/index.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link
  rel="stylesheet"
  href="{% static 'css/birds/bird-index.css' %}"
/>
{% endblock %} {% block content %}

<section class="page-header">
  <h1>Birds List</h1>
  <img
    src="{% static 'images/cool-cat.svg' %}"
    alt="A cool cat"
  />
  <img
    src="{% static 'images/happy-cat.svg' %}"
    alt="A happy cat"
  />
  <img
    src="{% static 'images/teacup-cat.svg' %}"
    alt="A cat in a teacup"
  />
  <img
    src="{% static 'images/cat-in-box.svg' %}"
    alt="A cat in a box"
  />
</section>

<section class="card-container">
  {% for bird in birds %}
  <div class="card">
    <a href="{% url 'bird-detail' bird.id %}">
    <div class="card-content">
      <div class="card-img-container">
        <img
          src="{% static 'images/sk8r-boi-cat.svg' %}"
          alt="A skater boy cat"
        />
    </div>
    <h2 class="card-title">{{ bird.name }}</h2>
    {% if bird.age > 0 %}
    <p>A {{ bird.age }} year old {{ bird.breed }}</p>
    {% else %}
    <p>A {{ bird.breed }} kitten.</p>
    {% endif %}
    <p><small>{{ bird.description }}</small></p>
  </div>
</a>
</div>
{% endfor %}
</section>

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link
  rel="stylesheet"
  href="{% static 'css/home.css' %}"
/>
{% endblock %} {% block content %}

<section class="logo-container">
  <div class="cat-container">
    <img
      src="{% static 'images/splash.svg' %}"
      alt="The Cat Collector Cat"
    />
  </div>
  <img
    src="{% static 'images/logotype.svg' %}"
    alt="Text reads: Cat Collector"
  />
</section>

{% endblock %}

main_app/templates/main_app/bird_confirm_delete.html
{% extends 'base.html' %}  
{% load static %} 
{% block content %}

<div class="page-header">
  <h1>Delete Bird ?</h1>
  <img src="{% static 'images/nerd-cat.svg' %}" alt="A cat using a computer" />
</div>

<h2>Are you sure you want to delete {{ bird.name }}?</h2>

<form action="" method="post" class="form">
  {% csrf_token %}
  <a href="{% url 'bird-detail' bird.id %}" class="btn secondary">Cancel</a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}
    

main_app/templates/main_app/bird_form.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}

<div class="page-header">
    <!-- Check if a cat object exists to determine if we're editing -->
    <img src="{% static 'images/nerd-cat.svg' %}" alt="A cat using a computer" />
    {% if bird %}
      <h1>Edit {{ bird.name }}</h1>
    {% else %}
      <h1>Add a bird</h1>
    {% endif %}
  </div>

 
</div>


<form action="" method="post" class="form-container">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}